### ISSUE TITLE
EBS volumes not se to be deleted at termination

### ISSUE THREAD

**Issue by glommer** [scylladb/cassandra-test-and-deploy#132]
EBS volumes created by the script are not set to be deleted at termination.
When terminating the instances manually, we are prompted about that.

**Comment by tzach** [comment]
@glommer thanks for reporting.
How to reproduce? what instance type are you using?

**Comment by glommer** [comment]
I am using i3.2xlarge - but since the EBS volumes are the root volumes,
they will likely happen with any.

To reproduce, just create servers and loaders with
cassandra-test-and-deploy, and try to terminate them manually in the web
interface. A dialog will open, saying that the volumes are not set to
delete-on-termination

**Comment by tzach** [comment]
Adding the following to ec2 module command should handle it, but since the root device is already removed on termination, not sure why it is needed.

```
        volumes:
          - device_name: /dev/sda1
            volume_size: 10
            delete_on_termination: true
```
